* Keyboard codes
  Measured using ZOLID flexable keyboard via xev:
  | key          | code |
  |--------------+------|
  | play/pause   |  172 |
  | stop         |  174 |
  | raise volume |  123 |
  | lower volume |  122 |
  | audio prev   |  173 |
  | audio next   |  171 |

  These keys worked without any system modifications in android.

  Keys from the USB HID Usage Tables, chapter 10
  | key         | code |
  |-------------+------|
  | volume up   |  128 |
  | volume down |  129 |
  and the rest is missing.

  Going to snoop the usb bus for keycodes. Need to say that the device will
  transmit multimedia keys using the usb descriptor. How this works is
  documented in https://github.com/ddrown/teensy_usb_android


* Interface to SSOP-18
** TC2030-STK
   Microchip cables that translate to small footprint pads on a pcb.

* Measurements of coat
  Setup:
  - 2.5mm female trs
    T = yellow
    R = red
    S = blue
  - 2.5mm male trs
    T = yellow
    R = white
    S = blue
** Resistance
   Connect F 2.5mmTRS to male 2.5mm of coat
   resistance between yellow/tip and blue/ground:
   | key | resistance, Ohm |
   |-----+-----------------|
   | +   | 5.575 k         |
   | >1  | 31.67 k         |
   | 11< | 46.28 k         |
   | 1<  | 19.96 k         |
   | -   | 10.018 k        |
** Current
   Connect F 2.5mm TRS to male 2.5mm of coat
   Connect F TRS to M TRS with fluke 8600A (uA) between yellow lines
   Connect M TRS to coat widget
   Connect coat widget to phone
   | key | current in uA |
   |-----+---------------|
   | +   | 106           |
   | >1  | 55.1          |
   | 11< | 43.21         |
   | 1<  | 70.12         |
   | -   | 91.39         |
** Voltage
   using scope: voltage between yellow/tip and blue/sleeve was 3V but fluctuated +-200mV

* Calculations
  With Vcc at 5V, and a 25k resistor to each rail with the coat keys inbetween:
  | Key     |    Rg |    Rv |    Rk | Ratio |
  |---------+-------+-------+-------+-------|
  | -       | 25000 | 25000 | 10000 |       |
  | rev     | 25000 | 25000 | 20000 |       |
  | play    | 25000 | 25000 | 46200 |       |
  | forward | 25000 | 25000 | 31600 |       |
  | plus    | 25000 | 25000 |  5600 |       |
